CREATE DATABASE IF NOT EXISTS Bakery;

USE Bakery; 

CREATE TABLE IF NOT EXISTS Products(
IDProducts INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FirstName VARCHAR (100),
Descripcion VARCHAR(100),
IDSize VARCHAR(100),
IDFlavors VARCHAR(100),
IDCategories VARCHAR(100),
IDPrice INT
);

CREATE TABLE IF NOT EXISTS Customers(
IDCustomers INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FirstName VARCHAR(100),
LastName VARCHAR(100),
Email VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS Orders(
IDOrders INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
IDCustomers INT,
IDProducts INT
);

CREATE TABLE IF NOT EXISTS Employees(
IDEmployees INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FirstName VARCHAR (100),
LastName VARCHAR(100),
Horario VARCHAR(100)
);






